### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by hshafique** [PayPal-Mobile/ios-here-sdk-dist#30]
Can you please provide installation instructions? Can this SDK be installed using CocoaPods?

Thanks

**Comment by ppmtscory** [comment]
All of the documentation that we have available is located in the Docs folder.  You should just need to import the appropriate bundles and framework that are located within the SDK folder of the repo.  Are you having issues with the import or errors due to that?  

As for CocoaPods, no, I'm not aware of a way to use that for installation.
