### ISSUE TITLE
Managing/supporting multiple users

### ISSUE THREAD

**Issue by JonChristensen** [PayPal-Mobile/ios-here-sdk-dist#47]
We have a kiosk app that users paypal here. And we need for several users in our company to be the main authenticating user for PayPal here -- these users will be the users that are actually near the kiosk installations -- we do not want to tell all of the the email and password of the main account that was used to setup PayPal here in the first place.

I can see that there is a way to add users to PayPal Here at this url: https://www.paypal.com/retailprofile/users/ but when I try to use one of those users to authenticate via OAuth it doesn't work.

How can I create new paypal here users that will fall under the overall company umbrella and be useable by the oauth sign in?

**Comment by djMax** [comment]
The conventional wisdom here would be that your "multiuser" stuff should be in your system rather than ours. You put your own login on top of your system that guards access to the single access/refresh token for the core account that you got by the main user having logged in and given consent. Part of the issue is exactly that consent, because it's a bit odd for a secondary account to grant consent for the whole account (which is where that consent is recorded).

In truth, I think this is the right approach as it's much easier to manage and lets you have short numeric pins or something more tuned to a purely-money-accepting application. Thoughts?

**Comment by JonChristensen** [comment]
Thanks @djMax you triggered and idea.  The issue right now is that we're bringing up a webview in the app where a user has to put in the paypal email and password of our main account holder. So that doesn't work in cases where a third party would need to install the app or uninstall/reinstall becuase we do not want to tell that third party the username and password of our main account.  BUT you made me wonder if it's possible to do all the oauth stuff on the server side thus obviating the need for that webview login piece.  I'm checking with the developer that knows more about this, but if you're around please feel free to respond.

**Comment by djMax** [comment]
Yes, that's definitely possible and a common integration pattern. There's a longer writeup about the overall concept [here](https://github.com/paypal/paypal-retail-node), and a server that will generate tokens for you. So if you put your own login system in front of it, then just dish out the access token once they login, or make the call on their behalf from the server, you'd be fine.
