### ISSUE TITLE
EMV?

### ISSUE THREAD

**Issue by centerax** [PayPal-Mobile/ios-here-sdk-dist#57]
Does this SDK already provide support for the new [chip card reader](https://www.paypal.com/us/webapps/mpp/emv) ?

Thanks.

**Comment by ppmtscory** [comment]
@centerax this indeed will support the EMV reader once everything has been tested and merged into the master branch.  Unfortunately I don't want to provide any hard dates for this because we're still working through some minor issues that have come up but hopefully it'll be available soon.  Please stay tuned...

**Comment by centerax** [comment]
Thanks for your quick reply @ppmtscory , looking forward to that merge :metal:

**Comment by ppmtscory** [comment]
Closing as 1.6 has been merged to Master.
