### ISSUE TITLE
[1.5.2] Unable to detect paypal card reader

### ISSUE THREAD

**Issue by rleiwang** [PayPal-Mobile/ios-here-sdk-dist#59]
I am using 1.5.2 SDK and having trouble to detect paypal card reader through the microphone. I included the regular release version of the framework from 1.5.2 branch.

NSLog(@"%@ version", [PayPalHereSDK sdkVersion]); 

printed

(null).nhw version

Is this right framework?

**Comment by rleiwang** [comment]
I moved to 1.6 SDK. It detects the reader now.

**Comment by ppmtscory** [comment]
Moving to 1.6 is the right move here, @rleiwang.  Unfortunately the 1.5.2 Sample was compiled against the "no hardware" (nhw) SDK so that's why it's not automatically detecting the reader.  Version 1.6 will soon be released to the Master branch anyway so priorities are currently being focused on that.
