### ISSUE TITLE
Tax not being calculated correctly in receipt 

### ISSUE THREAD

**Issue by brainfuel** [PayPal-Mobile/ios-here-sdk-dist#77]
taxInclusive = YES
Total price of transaction £1
Tax 20%

Test transaction with 1 item seems to work ok with £0.17 tax...
<img width="592" alt="screen shot 2016-01-30 at 01 36 59" src="https://cloud.githubusercontent.com/assets/4739285/12692662/4b395210-c6f2-11e5-9fb2-a054c710b185.png">

But if you add multiple small value items to the transaction it only calculates £0.03...

<img width="634" alt="screen shot 2016-01-30 at 01 22 57" src="https://cloud.githubusercontent.com/assets/4739285/12692690/9518ef9e-c6f2-11e5-987c-06ea697e24b4.png">

Any ideas on this?

**Comment by brainfuel** [comment]
On further testing it seems like the problem is not with small amounts but with multiple PPHInvoiceItem's , here I test with three lots of £1 items, and still get the wrong tax calculated...

<img width="638" alt="screen shot 2016-01-30 at 02 20 39" src="https://cloud.githubusercontent.com/assets/4739285/12693029/5a51605c-c6f8-11e5-9a16-21b603088589.png">

It appears to be only calculating the first item perhaps.

**Comment by brainfuel** [comment]
Logging invoice.tax before calling beginPaymentUsingUIWithInvoice seems to show that the tax on PPHInvoice is actually calculated correctly. So this could be a server side issue.

**Comment by ppmtscory** [comment]
@brainfuel my apologies for the delay on this.  Is this still something that's causing an issue or where do you stand currently with this?

**Comment by brainfuel** [comment]
Yes, I had to scrap itemised invoice and put the payment through as a sum of all items. Not ideal, but it was the only workaround I could think of. Would be great if it was fixed.  Thanks

**Comment by ppmtscory** [comment]
Thanks for the update, I will take a look.  Is this the only place that you reported this or did you also file a support ticket with the team?  If so, can I also get that ticket number from you so that I can consolidate everything?

**Comment by brainfuel** [comment]
This was the only place I reported the issue I believe.

**Comment by ppmtscory** [comment]
Great, thank you.  I'll update here once I run some tests to see what's happening.

**Comment by ppmtscory** [comment]
@brainfuel my sincere apologies for not updating this thread.  After digging further, the receipts are actually showing the way they are intended to show.  The intention was to show this way as a way to not clutter the receipt and, really, just to make it easier on the eyes.  The calculations are correct, and as you stated, available to you as such.  The reason it's showing this way on the receipt is to just simply say that all items that have the corresponding tax letter next to them, have the 0.17 tax included.  Instead of trying to calculate the total amount of tax, it instead is just telling the viewer of the receipt that each item above includes that tax amount.  I can see an argument being made for either case, but with this being a `taxInclusive` scenario, I believe the way it's listed out now is the way it needs to be, to be aesthetically pleasing.
