### ISSUE TITLE
App crash when use login with setupWithCredentials

### ISSUE THREAD

**Issue by JohanSimiCart** [PayPal-Mobile/ios-here-sdk-dist#89]
Hi,

I try use Rest Api: 

curl https://api.sandbox.paypal.com/v1/oauth2/token \
-H "Accept: application/json" \
-H "Accept-Language: en_US" \
-u "clientID:Secert" \
-d "grant_type=client_credentials"

And server respone access token. I use it and login paypal here with [PayPalHereSDK setupWithCredentials] but app crash and show error: "PPHAccessAccount fetchMerchantInfoAndThen:], /Users/mpavlinsky/Projects/PayPal/internal-sdk-dist/source/PayPalHereSDK/Core/PPHAccessAccount.m
OpenID userInfo request failed to return email. Perhaps the scope was invalid?
"

Please see it. Thanks

**Comment by JohanSimiCart** [comment]
@ppmtscory Ok. I will read Docs and try it again. Thanks!

**Comment by JohanSimiCart** [comment]
@ppmtscory Could you please provide me the account test or enable my Paypal account?

Paypal account: dong.le@trueplus.vn

Please help me. Thanks!

**Comment by ppmtscory** [comment]
When testing in the Sandbox, you'll just need to create your own US Business account with the first name of 'Ryan'.  This first name will trigger a success response when you send it through the onboarding that's outlined in that documentation.  Essentially....

- Login to developer.paypal.com with your live account
- Create a REST App that has the relevant products enabled (PPH, address info underneath Login With PayPal).  This will give you your Oauth credentials that you need.
- Create a US Business sandbox account to use as your 'merchant' account to receive the funds
- Send this business account through the onboarding flow outlined in the docs to enable PPH and also provide permissions to your dev account to process on it's behalf

**Comment by JohanSimiCart** [comment]
I try follow you and create new account with the first name of 'Ryan'. The account is apporve, I create a Rest App and enable all it. I try get access token with curl and use it login but the same error. 

Could you pleaes check my account sandbox:"chihoangvuong94@gmail.com"?

**Comment by ppmtscory** [comment]
Are you directing that new sandbox account through the onboarding flow?  If you're simply using that same CURL command then you're still creating a first party token.  In the onboarding flow, like the docs state, after the account is approved for PPH, then you direct them to the `/authorize` endpoint to provide permissions and then that flow returns an auth_code.  This auth_code is then used with the `/tokenservice` endpoint and the response will contain a refresh and access token.  The refresh token is what you will store so that you can generate further access tokens down the road as access tokens have an 8 hr expiry.

**Comment by JohanSimiCart** [comment]
Okie. I try it and success. Thank you!
